package com.example.docvault.domain.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a document stored in the vault.
 *
 * This is a Room entity that stores metadata about the document. The actual file content 
 * is stored as an encrypted file on the device's internal storage, and its path is 
 * referenced by [filePath].
 *
 * @property id Unique identifier for the document, auto-generated by Room.
 * @property title Human-readable title of the document.
 * @property category The category classification (e.g., ID, Marksheet).
 * @property fileType The MIME type of the document (e.g., "application/pdf", "image/jpeg").
 * @property filePath The absolute path to the encrypted file on disk.
 * @property size The size of the encrypted file in bytes.
 * @property createdAt Timestamp when the document was first added.
 * @property updatedAt Timestamp when the document was last modified (e.g., compressed).
 * @property tags List of optional tags for searching and filtering.
 */
@Entity(tableName = "documents")
data class Document(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val title: String,
    val category: DocumentCategory,
    val fileType: String,
    val filePath: String,
    val size: Long,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis(),
    val tags: List<String> = emptyList()
)
