package com.example.docvault.domain.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a log entry in the application's history.
 *
 * Each entry records a specific action taken by the user or the system on a document.
 * Entries persist even if the associated document is deleted, allowing for a 
 * historical audit trail.
 *
 * @property id Unique identifier for the log entry, auto-generated by Room.
 * @property actionType The type of action performed (e.g., UPLOADED, DELETED).
 * @property documentId The ID of the document this log refers to. Can be null if the document no longer exists.
 * @property documentName A snapshot of the document's name at the time the action occurred.
 * @property details Human-readable description of the action.
 * @property timestamp The time the action occurred.
 */
@Entity(tableName = "history_logs")
data class HistoryLog(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val actionType: HistoryActionType,
    val documentId: Long?,
    val documentName: String,
    val details: String,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Types of actions that can be recorded in the history logs.
 */
enum class HistoryActionType {
    /** Document added from camera, gallery, or scanner. */
    UPLOADED,
    /** Document converted from image to PDF. */
    CONVERTED,
    /** Document file size reduced via compression. */
    COMPRESSED,
    /** Document metadata (title, category, tags) modified. */
    EDITED,
    /** Document digitally signed (future feature). */
    SIGNED,
    /** Document removed from the vault. */
    DELETED,
    /** QR code scanned and content processed. */
    QR_SCANNED
}
